services:
  postgres:
    image: postgres:17
    container_name: url-shortener-postgres
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
    command: ["postgres", "-c", "timezone=America/Chicago"]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: