package com.example.urlshortener.orchestration.domain;
public enum WorkflowNode {
 REQUIREMENT_INGESTION, REQUIREMENT_NORMALIZATION, AMBIGUITY_CHECK, CLARIFICATION,
 BROWNFIELD_IMPACT, POLICY_EXCEPTION, DECOMPOSITION, DESIGN, ARCHITECTURE_APPROVAL,
 SECURITY, TEST_PLANNING, SYNCHRONIZE, IMPLEMENTATION, TESTING, DOCUMENTATION, VALIDATION,
 RELEASE_READINESS, RELEASE_APPROVAL, REPLAN, FALLBACK, COMPENSATION, SAFE_STOP, COMPLETED
}
